project/apps/main/models.py
# -*- coding: utf-8 -*-
__author__ = 'itmard'

# python imports
from hashlib import sha384
from datetime import datetime

# flask imports
from mongoengine import Document, StringField, DateTimeField, ReferenceField


# project imports


class User(Document):
    blog_title = StringField(required=True)
    username = StringField(required=True)
    email = StringField(required=True)
    __password = StringField(required=True)

    def __init__(self, *args, **kwargs):
        Document.__init__(self, *args, **kwargs)

        if 'password' in kwargs:
            self.password = kwargs['password']

    @property
    def password(self):
        raise IOError('No read access to this property!')

    @password.setter
    def password(self, password):

        # if self.__password was empty we will save password hexdigest
        if not self.__password:
            self.__password = sha384(password).hexdigest()

    def verify_password(self, password):
        return sha384(password).hexdigest() == self.__password

    def change_password(self, old_password, new_password):
        if self.verify_password(old_password):
            self.__password = sha384(new_password).hexdigest()
            return True
        return False

    def reset_password(self):
        self.__password = None

    meta = {
        'indexes': ['username']
    }


class Post(Document):
    user_id = ReferenceField('User', required=True)
    post_title = StringField(required=True)
    description = StringField(required=True)
    created_on = DateTimeField(default=datetime.utcnow)

    meta = {
        'indexes': ['user_id']
    }

project/apps/main/forms.py
# -*- coding: utf-8 -*-
__author__ = 'itmard'

# flask imports
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, SubmitField, PasswordField, validators


class SignupForm(Form):
    blog_title = StringField(validators=[validators.DataRequired()])
    username = StringField(validators=[validators.DataRequired()])
    email = StringField(validators=[validators.Email(),
                                    validators.DataRequired()])
    password = PasswordField(validators=[validators.DataRequired(),
                                         validators.Length(min=6)])
    submit = SubmitField()


class EditForm(Form):
    blog_title = StringField(validators=[validators.optional()])
    username = StringField(validators=[validators.optional()])
    email = StringField(validators=[validators.Email(),
                                    validators.optional()])
    old = PasswordField(validators=[validators.Optional(),
                                    validators.Length(min=6)])
    new = PasswordField(validators=[validators.Optional(),
                                    validators.Length(min=6)])
    submit = SubmitField()


class LoginForm(Form):
    username = StringField(validators=[validators.DataRequired()])
    password = PasswordField(validators=[validators.DataRequired()])
    submit = SubmitField()


class PostForm(Form):
    post_title = StringField(validators=[validators.DataRequired()])
    description = TextAreaField(validators=[validators.DataRequired()])
    submit = SubmitField()


class EditPostForm(Form):
    post_title = StringField(validators=[validators.optional()])
    description = TextAreaField(validators=[validators.optional()])
    submit = SubmitField()

project/__init__.py
# -*- coding: utf-8 -*-
__author__ = 'itmard'

from project.application import create_app

project/apps/__init__.py
# -*- coding: utf-8 -*-
__author__ = 'itmard'

project/apps/main/__init__.py
# -*- coding: utf-8 -*-
__author__ = 'itmard'

# flask imports
from flask import Blueprint


main = Blueprint('main', __name__)

from . import views

project/apps/main/views.py
# -*- coding: utf-8 -*-
__author__ = 'itmard'

# python import
from datetime import datetime

from mongoengine import DoesNotExist


# flask import
from flask import session, g, abort, render_template, \
    redirect, url_for, flash

# project imports
from project.apps.main import main
from project.utils import edit_property
from project.access import not_login_allowed, login_required
from forms import SignupForm, LoginForm, EditForm, PostForm, \
    EditPostForm
from models import User, Post


@main.route('/', methods=['GET', 'POST'])
@main.route('/login', methods=['GET', 'POST'])
@not_login_allowed
def login():
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user_obj = User.objects.get(username=form.username.data)

            if user_obj.verify_password(form.password.data):
                session['user'] = str(user_obj.pk)
                return redirect(url_for('main.index'))
        except(DoesNotExist):
            pass
        flash('User or password is wrong maybe user does not exist')
    return render_template('login.html', form=form)


@main.route('/logout/', methods=['GET'])
@login_required
def logout():
    del session['user']
    return redirect(url_for('main.login'))


@main.route('/signup/', methods=['GET', 'POST'])
@not_login_allowed
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        try:
            User.objects.get(username=form.username.data)
            flash('User with this username exists')
            return redirect(url_for('main.signup'))
        except(DoesNotExist):
            user_obj = User(username=form.username.data)
            user_obj.blog_title = form.blog_title.data
            user_obj.email = form.email.data
            user_obj.password = form.password.data
            user_obj.save()
            flash('Registered')
            return redirect(url_for('main.login'))
    return render_template('signup.html', form=form)


@main.route('/index/', methods=['GET'])
@login_required
def index():
    user_obj = g.user
    user_posts = Post.objects(user_id=user_obj).order_by('-created_on')
    return render_template('index.html', posts=user_posts)


@main.route('/edit/', methods=['GET', 'POST'])
@login_required
def edit():
    form = EditForm()
    if form.validate_on_submit():
        user_obj = g.user
        user_obj.blog_title = edit_property(user_obj.blog_title,
                                            form.blog_title.data)
        user_obj.email = edit_property(user_obj.email, form.email.data)
        if form.username.data:
            try:
                User.objects.get(username=form.username.data)
                form.username.errors.append('User Exist')
            except(DoesNotExist):
                user_obj.username = form.username.data

        if form.new.data and form.old.data:
            # so user wanted to change his password to
            if not user_obj.change_password(form.old.data, form.new.data):
                form.old.errors.append('Wrong password.')

        elif form.new.data or form.old.data:
            if form.new.data:
                form.new.errors.append('Input old password.')
            else:
                form.old.errors.append('Input new password.')

        user_obj.save()
        flash('Updated')

    return render_template('edit.html', form=form)


@main.route('/post/', methods=['GET', 'POST'])
@login_required
def post():
    form = PostForm()
    if form.validate_on_submit():
        post_obj = Post(post_title=form.post_title.data)
        post_obj.description = form.description.data
        post_obj.user_id = g.user
        post_obj.save()
        flash('Created')
        return redirect(url_for('main.post'))
    return render_template('post.html', form=form)


@main.route('/<string:user_name>/')
def show_posts(user_name):
    try:
        user_obj = User.objects.get(username=user_name)
        user_posts = Post.objects(user_id=user_obj).order_by('-created_on')[:3]
        print user_obj.blog_title
        return render_template('show_posts.html', posts=user_posts)

    except(DoesNotExist):
        return abort(404)


@main.route('/post/delete/<string:pk>/')
@login_required
def delete_post(pk):
    try:
        post_obj = Post.objects.get(pk=pk)
        post_obj.delete()
        post_obj.save()
        flash('Deleted')
    except(DoesNotExist):
        flash('Does not exist')
    return redirect(url_for('main.index'))


@main.route('/post/edit/<string:pk>/', methods=['GET', 'POST'])
@login_required
def edit_post(pk):
    form = EditPostForm()
    try:
        post_obj = Post.objects.get(pk=pk)
    except(DoesNotExist):
        flash('Does not exist')
        return abort(404)

    if form.validate_on_submit():
        post_obj.post_title = edit_property(post_obj.post_title,
                                            form.post_title.data)
        post_obj.description = edit_property(post_obj.description,
                                             form.description.data)
        post_obj.created_on = datetime.utcnow()
        post_obj.save()
        flash('Edited')
    return render_template('post_edit.html', form=form)

project/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Prefect Blog{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        body{
            font-family: 'Ubuntu', 'Lucida Grande', 'Lucida Sans Unicode', 'Geneva', 'Verdana', sans-serif;
        }
    </style>
{% endblock %}
{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand navbar-right" href="{{ url_for('main.index') }}" >Prefect Blog  </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.post') }}">Add new post</a></li>
                    <li><a href="{{ url_for('main.edit') }}">Edit Profile</a></li>
                    <li><a href="{{ url_for('main.show_posts', user_name=g.user.username) }}">Show my blog</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if g.user %}
                        <li><a href="{{ url_for('main.logout') }}">{{ g.user.username }} (Logout) </a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.login') }}">login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
{% endblock %}

project/templates/edit.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}Prefect Blog - Edit profile info{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    form{
        width: 400px;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h2>Edit info</h2>
    {{ wtf.quick_form(form) }}
{% endblock %}

project/templates/form.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'))}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif %}">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {{field(class="form-control", **kwargs)|safe}}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {{field(class="form-control", **kwargs)|safe}}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="") %}
<form novalidate=""
  {%- if action %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if enctype %} enctype="{{enctype}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

project/templates/index.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}{{ g.user.blog_title }}{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    form{
        width: 400px;
    }
    td{
        font-size: 18px;
    }
    textarea{
        height: 200px !important;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h1>Welcome {{ g.user.username }}</h1>
    <h4 class="pull-right"><a href="{{ url_for('main.post') }}">Add new post</a></h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Post title</th>
                <th>Options</th>
            </tr>
        </thead>
        {% for post in  posts %}
            <tr>
                <td>{{ post.post_title }}</td>
                <td><a class="btn btn-danger" href="{{ url_for('main.delete_post', pk=post.pk) }}">Delete</a>
                    <a class="btn btn-primary" href="{{ url_for('main.edit_post', pk=post.pk) }}" >  Edit </a></td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

project/templates/login.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}Login to Prefect Blog{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    .main,form{
        width: 400px;
    }
    </style>
{% endblock %}
{% block page_content %}
    <div class="main">
    <h2>Login</h2><h4 class="pull-right"><a href="{{url_for('main.signup')}}">Register</a></h4>

    {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

project/templates/post.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}Prefect Blog - Add new post{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    form{
        width: 400px;
    }
    textarea{
        height: 200px !important;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h2>Add Post</h2>
    {{ wtf.quick_form(form) }}
{% endblock %}

project/templates/post_edit.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}Prefect Blog - Edit Posts{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    form{
        width: 400px;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h2>Edit Post</h2>
    {{ wtf.quick_form(form) }}
{% endblock %}

project/templates/show_posts.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}{{ g.user.blog_title }}{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
    form{
        width: 400px;
    }
    textarea{
        height: 200px !important;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h1>{{ g.user.blog_title }}</h1>
    {% for post in posts  %}
        <h2>{{post.post_title}}</h2>
        <p>{{ post.description }}</p>
        <h6>{{ post.created_on.strftime('%Y-%m-%d %H:%M') }}</h6>
        <hr/>

    {% endfor %}
{% endblock %}

project/templates/signup.html
{% extends "base.html" %}
{% import "form.html" as wtf %}


{% block title %}Create new blog{% endblock %}
{% block styles %}
    {{ super() }}

    <style>
    form{
        width: 400px;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h2>Register</h2>
    {{ wtf.quick_form(form) }}
{% endblock %}